name: Auto Comment on Job Application

on:
  issues:
    types: [opened]

jobs:
  add_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add a comment to the issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Use the secret token
          script: |
            const fs = require('fs').promises;
            const path = require('path');
            const workspace = process.env.GITHUB_WORKSPACE; // Add this line

            async function run() {
              try {
                const commentBody = await fs.readFile(path.join(workspace, '.github/workflows/comment-body.md'), 'utf8'); // Update this line
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.payload.issue.number,
                  body: commentBody
                });
              } catch (error) {
                console.error('Error reading file:', error);
                throw error;
              }
            }

            run();
