name: Auto Comment on Job Application

on:
  issues:
    types: [opened]

jobs:
  add_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add a comment to the issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Use the secret token
          script: |
            const fs = require('fs');
            const path = require('path');
            const commentBody = fs.readFileSync(path.resolve(__dirname, './comment-body.md'), 'utf8');
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body: commentBody
            });