name: Auto Comment on Job Application

on:
  issues:
    types: [opened]

jobs:
  add_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add a comment to the issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}  # Use the secret token
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body: `
              ### Thank you for your application! 🎉  
              
              ## ✅ What's next?
              **Read & Familiarize Yourself with Our Guidelines**  
                 - [🔗 Holdex Guidelines](https://github.com/holdex/developers/blob/main/.github/CONTRIBUTING.md)  
              
              ---  
              
              ## 🎯 Trial Phase  
              After this step, you will begin your **Trial**, which consists of two tasks:
              
              - **Submit Your Profile Through a PR**  
                - The PR must follow our [Guidelines](https://github.com/holdex/developers/blob/main/.github/CONTRIBUTING.md).  
                - A PR that doesn’t follow the Guidelines will result in rejection.
              
              - **Complete a Technical Task**  
                - This will be assigned manually by **Mark Curchin** (@markholdex).
              
              ---  
              
              ## How to Submit Your Profile  
              
              After the issue is created, please submit a **Pull Request (PR)** adding your profile to our JSON file.  
              
              ### Steps:
              1. **Fork this repository**  
              2. **Edit** \`profile-submission.json\`  
                 - Add your details using this format:  
                 
                 \`\`\`json
                     {
                       \"github_handle\": \"your_github_username\",
                       \"full_name\": \"Your Name\",
                       \"github_trial_issue_link\": \"https://github.com/holdex/trial/issues/your_issue_number\"
                     }
                 \`\`\`  
              3. **Commit your changes and create a Pull Request (PR)**  
              4. **Wait for review and approval**  
              
              <hr>
              
              If you have any questions, feel free to ask in this issue! 😉

              <hr>
              `
            });
 
